version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: ugto_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: ugto_db

  mongo-express:
  image: mongo-express:latest
  container_name: mongo_express
  restart: always
  ports:
    - "8081:8081"
  environment:
    ME_CONFIG_MONGODB_SERVER: mongo
    ME_CONFIG_MONGODB_PORT: 27017
    ME_CONFIG_BASICAUTH_USERNAME: ad
    ME_CONFIG_BASICAUTH_PASSWORD: ad
    ME_CONFIG_BASICAUTH_REALM: "Mongo Express"
  depends_on:
    - mongo
